language: latex
sudo: required
before_install:
- sudo apt-get -qq update
- sudo apt-get install texlive texlive-latex3
- sudo apt install texlive-latex-extra
- chmod +x build.sh
- chmod +x travis_deploy.sh
script:
- "./build.sh"
deploy:
  provider: script
  script: "./travis_deploy.sh"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - ENCRYPTION_LABEL="81d85cdc1787"
  - COMMIT_AUTHOR_EMAIL="xcesivio@gmail.com"
  - COMMIT_AUTHOR="xcesiv"
  - PUSH_REPO="git@github.com:durachain:whitepaper.git"
  - secure: a43RkClx+qp2FjZOyEys+//EVLXb2D9yhr7DX5rDs1cch7Dpnptn9cLBIpnqZYc8BK2hpGXFaJZZbHbBd7O94swXc6jtxrQ44ziZEpTPowZxamaaD1VwY6Bjhlb13yBNl1Ve/JDxLlaHqZ/jVG+24siDJ+GZHX6t0mOiXciSE92mzFP9S6nND9qr1KJA86H8iqE10975f/OE8ZzmkMA81FPg6mgDy9XWhwZeSwpbVPdSF35djQIygFo4GXiig/T+UDuM/68zTrybi3/pNy1TCE3t/bJpMH+NRFT6Uftxv20M3CTsTY72ss67Pag7wQbE0Fif0Oho6Pta0GTB4NufmMKDlJNj8wSlpQf0hWv2MZeWYj1a0yafTfJ8swXWFM4iuou4YzGeqj9PBSPi/BPaic27GlyUBZLp32X275uHeVilv8BrzA4Of2NlYQ1mlOmqqpW7o//jtamNzKR6T8+z+NK+qi9AsISFahI37uUN62/UZlXOYTkGhljHlNYx7mfrH3YhidYxBggN44Er/0oDXxGN+R14E/Bzy3zFTihVQEMhBcI9XXZadjJ1qIHyXxLKro/GJ7uZJLdB+JLk29o0BID//0IC4FyIEvd0STXf9b/wxN/6yx4xBhx9J9rVIcl+T25qWnoOv+ZLNv5DuWgFcIIpUf4AnyT6+s9breJtdTM=
